---
title: "file_formatting"
format: html
editor: visual
---

# Downloading .zip file to home directory

```{bash}
# On the home terminal
# Not within CREATE 
# scp -i ~/.ssh/create_msc k25055720@hpc.create.kcl.ac.uk:/scratch/grp/msc_appbio/DCDM/Group3/data/*.csv .
```

# Load Libraries

```{r}
install.packages("readr")
install.packages("dplyr")
install.packages("purrr")
install.packages("tools")

library(readr)
library(dplyr)
library(purrr)
library(tools)

```

# Check .csv file formats

```{r}

folder_path <- "/scratch/grp/msc_appbio/DCDM/Group3/raw_data"
#file_list <- list.files(folder_path, full.names = TRUE, recursive = T)
# print(file_list)
# 24'358 total files
# file <- file_list[1]

# Function to select variable names from the file
variable_selection <- function(file) {
    df <- read_delim(file, delim = ",", col_names = c("variable", "value"),
                     show_col_types = FALSE, trim_ws = TRUE)
    df$variable
  }

# Recursive function to process files

check_file_format <- function(folder_path) {
  
  # Find csv files
  file_list <- list.files(folder_path, full.names = TRUE, recursive = T)
  message("Folder Exists. There are: ", length(file_list), " CSV files.")
  
  # Extract variables from each file
  variables <- map(file_list, variable_selection)
  names(variables) <- file_list
  
  # Set a list of reference variables (from the first file)
  reference_variable <- variables[[1]]
  
  # Compare each file variables to the reference
  file_format_result <- map_df(seq_along(variables), function(i) {
    variables_names <- variables[[i]]
    file_name <- basename(file_list[[i]])
    
    if (is.na(variables_names[1])) {
      return(data.frame(file = file_name, status = "error", missing = NA, extra = NA))
    }
    
    missing_variables <- setdiff(reference_variable, variables_names)
    extra_variables <- setdiff(variables_names, reference_variable)
    
    data.frame(
      file = file_name,
      status = ifelse(length(missing_variables) == 0 && length(extra_variables) == 0, "OK", "MISMATCH"),
      missing = paste(missing_variables, collapse = "; "),
      extra = paste(extra_variables, collapse = "; "),
      stringsAsFactors = FALSE
    )
  })
  
  count_ok <- sum(file_format_result$status == "OK")
  count_mismatch <- sum(file_format_result$status == "MISMATCH")
  
  message(count_ok, " files are OK")
  message(count_mismatch, " files have variable mismatches")
  
  return(file_format_result)
  
}


```

## Run Function

```{r}

folder_path <- "/scratch/grp/msc_appbio/DCDM/Group3/raw_data"

output_file_check <- check_file_format(folder_path)

# Output:
# Folder Exists. There are: 25358 CSV files.
# 25116 files are OK
# 242 files have variable mismatches

```

# Extract Mismatched files

```{r}

mismatched_files <- output_file_check %>%
  filter(status != "OK") %>%
  pull(file)

file_list_mismatched <- file.path("/Users/georgiagoddard/Desktop/data/Group3/data_edited", mismatched_files)

# Looking into this file, the only problem is case sensitivity.
# Except the capitalization isn't consistent at all. 

# 242 mismatched files extracted 

```

# Fix Case Sensitivity in files

```{r}
# DOES NOT WORK
# Could be improved by only iterating through "mismatched files"

# FUNCTION DOES NOT WORK DONT RUN IT
fix_case_sensitivity <- function(folder_path) {
  file_list <- list.files(folder_path, full.names = TRUE, recursive = T)
  message("Folder Exists. There are: ", length(file_list), " CSV files.")
  
  for (file in file_list) {
    df <- read_delim(file, delim = ",", col_names = c("variable", "value"),
                     show_col_types = FALSE, trim_ws = TRUE)
    }
  
    df$variable <- tolower(df$variable)
    write_delim(df, file, delim = ",")
    
    message("All files have been processed and converted to lowercase variable names.")
  
}

```

